#!/bin/bash

###TEST
../test/e-reset/build.sh
../test/e-test/build.sh 
../test/e-extmem-test/build.sh	
../test/e-mem-test/build.sh   
../test/e-reset/build.sh	    
../test/e-write-word/build.sh
../test/e-main/build.sh		
../test/e-read-buf/build.sh   
../test/e-test/build.sh
../test/e-matmul-test/build.sh	
../test/e-read-word/build.sh  
../test/e-write-buf/build.sh
###APPS
../apps/dotproduct/build.sh        
../apps/e-fill-mem/build.sh    
../apps/matmul-64/build.sh
../apps/matmul-16/build.sh
../apps/e-bandwidth-test/build.sh  
../apps/e-dump-mem/build.sh        
../apps/e-mem-sync/build.sh    
../apps/fft2d/build.sh
../apps/e-dump-regs/build.sh       
../apps/e-toggle-led/build.sh
###EMESH  
../emesh/emesh_bandwidth_all2one/build.sh
../emesh/emesh_bandwidth_neighbour/build.sh
#../emesh/emesh_traffic/build.sh-->broken FIX!!!!x
../emesh/emesh_bandwidth_bisection/build.sh
../emesh/emesh_read_latency/build.sh
###
